version: "3.3"

services:

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  web:
    image: "cchalop1/epitech-security-web:latest"
    container_name: "web"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`epitech-owasp-2022.com`)"
      - "traefik.http.routers.web.entrypoints=web"

  api:
    image: "cchalop1/epitech-security-api:latest"
    container_name: "api"
    restart: always
    # TODO: move this env to secrests
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_VALIDATION_KEY=${JWT_VALIDATION_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.epitech-owasp-2022.com`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.port=5000"
