version: "3.9"

services:
  app:
    container_name: Attack_Defend_api
    build:
      context: ./API
      dockerfile: ./Dockerfile
    env_file:
      - ./API/.env
    restart: always
    ports:
      - 5000:5000
