version: "3.9"

services:
  app:
    container_name: Attack_Defend_api
    build:
      context: ./
      dockerfile: ./API/Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_VALIDATION_KEY=${JWT_VALIDATION_KEY}
    restart: always
    ports:
      - 5000:5000
