name: deploy application

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: build docker image and deploy on vps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Front
          push: true
          tags: cchalop1/epitech-security-web:latest
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./API
          push: true
          tags: cchalop1/epitech-security-api:latest
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/root/"
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker-compose stop
            docker-compose pull
            docker-compose up -d
      
      # - name: Checkout
      #   uses: actions/checkout@v2
      # - name: Set up Python 3.7
      #   uses: actions/setup-python@v1
      #   with:
      #     python-version: 3.7
      # - name: Run playbook
      #   uses: dawidd6/action-ansible-playbook@v2
      #   with:
      #     playbook: deploy.yml
      #     directory: ./
      #     key: ${{secrets.SSH_PRIVATE_KEY}}
      #     inventory: |
      #       [all]
      #       ansible_host=epitech-owasp-2022.com
      #       ansible_user=root
            
      #       [defaults]
      #       host_key_checking = False
      #     options: |
      #       --inventory .hosts
      #       --extra-vars hello=there
      #       --verbose
